theme = "catppuccin-mocha"

[window]
mode = "Maximized"
decorations = "Transparent"

[renderer]
strategy = "Game"
disable-unfocused-render = false

[navigation]
mode = "Bookmark"

[fonts]
family = "MesloLGM Nerd Font"

[shell]
program = "pwsh"
args = []