## Global

# NOTE: This is global for linux and windows dont't use paths!!

[general]

import = [
    "theme.toml"
]

[window]

startup_mode = "Maximized"

[font]

normal = { family = "MesloLGM Nerd Font", style = "Regular" }
size = 10