[colors.primary]

foreground = "#ffffff"
background = "#000000"
dim_foreground = "#c2c3c7"
bright_foreground = "None"

[colors.normal]

black = "#000000"
red = "#ff004d"
green = "#00b251"
yellow = "#ffec27"
blue = "#29adff"
magenta = "#83769c"
cyan = "#00a5a1"
white = "#ffacc5"

[colors.bright]

black = "#125359"
red = "#ff4e84"
green = "#00e436"
yellow = "#90ec42"
blue = "#82b8c8"
magenta = "#bd9adf"
cyan = "#04f1ec"
white = "#fff1e8"

[colors.dim]

black = "#0f0f0f"
red = "#8e0037"
green = "#066b34"
yellow = "#867c0b"
blue = "#186a9e"
magenta = "#56427c"
cyan = "#056765"
white = "#636363"


