# Based on Hydrogen modified by Jan Palma

spacing         = 1
padding         = 0
hide_ascii      = false
prefer_small_ascii = false
separator       = ""
key_color       = "#bcdf59"
separator_color = "#505050"

[palette]
type = "Full"
visible = false

[bar]
glyph           = "󰧞"
symbol_open     = '['
symbol_close    = ']'
hide_delimiters = true
visible         = true

[box]
border          = "plain"
visible         = true

[box.inner_margin]
x               = 1
y               = 0

[randomize]
key_color       = false
separator_color = false

[keys]
host            = "󰀄"
kernel          = "󰫸"
battery         = "󰄌"
os              = "󰾞"
de              = "󰠱"
wm              = "󰖯"
distro          = "󰫱"
terminal        = ""
shell           = ""
packages        = "󰏓"
uptime          = "󱑍"
memory          = "󰍛"
machine         = "󰟗"
local_ip        = "󰛳"
backlight       = "󰳲"
resolution      = "󰍹"
cpu_load        = "󰓅"
cpu             = "󰘚"
gpu             = "󰲙"
disk_space      = ""
